from setuptools import setup, find_packages
from functools import reduce

long_description = """A fork of the AwesomeMRC repo."""

version = '0.1.0'

# with open("aif360/version.py", 'w') as f:
#     f.write('# generated by setup.py\nversion = "{}"\n'.format(version))

extras = {
#     'OptimPreproc': ['cvxpy>=1.0'],
#     'LFR': ['numba>=0.42.0'],
#     'AdversarialDebiasing': ['tensorflow>=1.13.1,<2'],
#     'DisparateImpactRemover': ['BlackBoxAuditing'],
#     'LIME': ['lime'],
#     'ART': ['adversarial-robustness-toolbox>=1.0.0'],
    'notebooks': ['jupyter', 'tqdm']
}
# extras['tests'] = reduce(lambda l1, l2: l1+l2, extras.values(), ['pytest>=3.5'])
# extras['docs'] = ['sphinx', 'sphinx_rtd_theme']
# extras['all'] = list(reduce(lambda s, l: s.union(l), extras.values(), set()))

setup(name='AwesomeMRC',
      version=version,
      description='retro-reader conversational agent',
      author='AwesomeMRC developers',
#       author_email='',
      url='https://github.com/bhomass/AwesomeMRC.git',
      long_description=long_description,
      long_description_content_type='text/markdown',
      license='MIT License',
      packages=[pkg for pkg in find_packages()],
      python_requires='>=3.5',
      install_requires=[
          'numpy>=1.19.5',
          'scipy>=1.5.3',
          'pandas>=0.24.0',
          'tqdm',
          'requests',
          'tensorboardX',
          'scikit-learn',
          'sentencepiece',
          'sacremoses',
          'regex',
          'boto3',
          'apex=0.1'
      ],
      extras_require=extras,
      package_data={'NERO': ['data/*', 'data/*/*']},
      include_package_data=True,
      zip_safe=False)
